# Generated by Django 3.0.5 on 2020-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvant_proj', '0002_kvant_projects_kvantorianec_kvantum_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key_words',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterModelOptions(
            name='kvant_projects',
            options={'verbose_name': 'Проект кванторианцев', 'verbose_name_plural': 'Проекты кванторианцев'},
        ),
        migrations.AlterModelOptions(
            name='kvantorianec',
            options={'verbose_name': 'Кванторианец', 'verbose_name_plural': 'Кванторианцы'},
        ),
        migrations.AlterModelOptions(
            name='kvantum',
            options={'verbose_name': 'Квантум', 'verbose_name_plural': 'Квантумы'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Наставник', 'verbose_name_plural': 'Наставники'},
        ),
        migrations.AlterField(
            model_name='kvantorianec',
            name='b_date',
            field=models.DateField(blank=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='kvantum',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='описание квантума'),
        ),
        migrations.AlterField(
            model_name='kvantum',
            name='kvantum_logo',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='логотип квантума'),
        ),
        migrations.AlterField(
            model_name='master',
            name='b_date',
            field=models.DateField(blank=True, verbose_name='дата рождения преподователя'),
        ),
    ]
