# Generated by Django 3.0.5 on 2020-04-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvant_proj', '0003_auto_20200423_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvant_projects',
            name='low_description',
            field=models.CharField(default='01.01.1990', max_length=5000, verbose_name='краткое описание проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kvant_projects',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='описание проекта'),
        ),
        migrations.AlterField(
            model_name='kvant_projects',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='kvantorianec',
            name='fio',
            field=models.CharField(max_length=75, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='master',
            name='fio',
            field=models.CharField(max_length=75, verbose_name='ФИО преподователя'),
        ),
    ]
